# Generated by Django 4.2.4 on 2023-10-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_address',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
    ]
