# Generated by Django 4.2.4 on 2023-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0002_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laundryId', models.CharField(max_length=100)),
                ('shopName', models.CharField(max_length=100)),
                ('contactNo', models.CharField(max_length=20)),
                ('emailAddress', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('addressDetails', models.CharField(max_length=255)),
                ('businessLicensePhoto', models.ImageField(upload_to='business_license_photos/')),
                ('fullName', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=20)),
                ('icNo', models.CharField(max_length=20)),
                ('registerDateTime', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('userType', models.CharField(max_length=20)),
                ('notification', models.BooleanField()),
                ('setup', models.BooleanField()),
                ('isBreak', models.BooleanField()),
                ('balance', models.FloatField()),
                ('ratingsAverage', models.FloatField()),
            ],
        ),
    ]
